sudo: required
language: bash

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - DOCKER_VERSION=1.10.1-0~trusty
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

before_install:

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-engine=${DOCKER_VERSION}

  # Install envtpl for easy templating
  - sudo pip install envtpl

  # Login to hub.docker.com
  - docker login --email $DOCKER_EMAIL --username $DOCKER_USER --password $DOCKER_PASS

script:
  # Change this later.
  - make publish
