sudo: required
language: bash

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - DOCKER_VERSION=1.10.1-0~trusty
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

before_install:

  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-engine=${DOCKER_VERSION}

  # Install envtpl for easy templating
  - sudo pip install envtpl

  # Login to hub.docker.com
  - docker login --email not@val.id --username $DOCKER_USER --password $DOCKER_PASS

script:
  # Change this later.
  - make publish

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$(make version)
  - echo "GIT_TAG=$GIT_TAG"
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git tag $GIT_TAG -f -a -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/jobs/$TRAVIS_JOB_ID"
    || true
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git push -q https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG --tags || true
