name: docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login Docker Hub
        run: docker login --username $DOCKER_USER --password $DOCKER_PASS
      - run: |
          make publish
          make publish-github-registry
