name: main

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GH_PKG_RW_TOKEN }}
  CI_BUILD_NUMBER: ${{github.run_number}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          # use Java 8
          java-version: adopt@1.8
      - name: build and publish image
        run: make publish
