name: main

on:
  push:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GH_PKG_RW_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          # use Java 8
          java-version: adopt@1.8
      - name: build and publish image
        run: make publish-github-registry
